# yamllint configuration
# Docs: https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'True', 'False']
    
  # Disable strict formatting rules that conflict with standard ROS 2 configs
  document-start: disable
  new-line-at-end-of-file: disable
  trailing-spaces: disable
  empty-lines: disable
  comments-indentation: disable
